# .github/workflows/playwright.yml
name: Playwright Tests

on:
  push:
    branches: ["dev*"]
  pull_request:
    branches: ["dev*"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Angular deps
        run: |
          set -e
          npm ci --legacy-peer-deps --no-audit --no-fund || npm install --legacy-peer-deps --no-audit --no-fund

      - run: npx ng version
      - name: Build Angular (production)
        run: npx ng build --configuration production

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**

  tests:
    runs-on: ubuntu-latest
    needs: [build-angular]
    env:
      NPM_CONFIG_AUDIT: "false"
      NPM_CONFIG_FUND: "false"
      PW_FORBID_ONLY: "1"
      QA_URL: http://localhost:4200
      QA_EXTERNAL_URL: 'https://www.globalsqa.com/demo-site/draganddrop/#Photo%20Manager'
      ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN || '' }}
      ARGOS_BRANCH: ${{ github.ref_name }}
      ARGOS_BASE_BRANCH: main
      ARGOS_COMMIT: ${{ github.sha }}
      ARGOS_CI: github-actions
      ARGOS_PARALLEL_TOTAL: "1"
      ARGOS_PARALLEL_INDEX: "0"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install test deps
        run: |
          set -e
          npm ci --legacy-peer-deps --no-audit --no-fund || npm install --legacy-peer-deps --no-audit --no-fund

      - name: Defocus tests (remove .only)
        run: node scripts/strip-only.js

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Argos env summary
        run: |
          echo "ARGOS token set?: $([ -n \"$ARGOS_TOKEN\" ] && echo yes || echo no)"
          echo "ARGOS_BRANCH=$ARGOS_BRANCH"
          echo "ARGOS_BASE_BRANCH=$ARGOS_BASE_BRANCH"
          echo "ARGOS_COMMIT=$ARGOS_COMMIT"
          echo "ARGOS_CI=$ARGOS_CI"

      - name: Install Argos (lenient)
        id: argos_install
        if: ${{ env.ARGOS_TOKEN != '' }}
        continue-on-error: true
        run: npm install -D --no-save --legacy-peer-deps --no-audit --no-fund @argos-ci/playwright argos

      - name: Verify Argos reporter is resolvable
        if: ${{ env.ARGOS_TOKEN != '' && steps.argos_install.outcome == 'success' }}
        run: node -e "console.log(require.resolve('@argos-ci/playwright')); console.log('Argos reporter RESOLVED ✅')"

      - name: Playwright tests (with Argos)
        if: ${{ env.ARGOS_TOKEN != '' && steps.argos_install.outcome == 'success' }}
        env:
          DEBUG: "argos:*"
        run: npx playwright test -c playwright.argos.config.ts --reporter=line

      - name: Playwright tests (no Argos)
        if: ${{ env.ARGOS_TOKEN == '' || steps.argos_install.outcome != 'success' }}
        run: npx playwright test --reporter=line

      # Explicit upload so a build always appears in Argos UI
      - name: Upload snapshots to Argos (CLI)
        if: ${{ env.ARGOS_TOKEN != '' }}
        run: |
          if [ -d ".argos-screenshots" ]; then
            echo "Found snapshots, uploading via Argos CLI…"
            npx -y argos upload ./.argos-screenshots
          else
            echo "No .argos-screenshots directory found."
          fi

      - name: "Argos debug: list snapshots"
        if: always()
        run: |
          echo "Contents of ./.argos-screenshots (if any):"
          ls -la .argos-screenshots || echo "(no directory)"

      - name: "Upload Argos debug artifact"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: argos-snapshots
          path: .argos-screenshots/**
          if-no-files-found: ignore

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report